### ISSUE TITLE
How do you set('args')?

### ISSUE THREAD

**Issue by bdirito** [rocky/trepanjs#2]
I have tried the following:

```
(trepanjs) show('args')
args needs an Array parameter, got: undefined
(trepanjs) set('args', ['how', 'do', 'i', 'set'])
args needs an Array parameter, got: undefined
(trepanjs) set('args', ('lisp', 'format', 'perhaps'))
args needs an Array parameter, got: perhaps
(trepanjs) set('args', ["double", "quotes"])
args needs an Array parameter, got: undefined
(trepanjs) set('args', ("lisp", "double", "quotes"))
args needs an Array parameter, got: quotes
(trepanjs) set('args', '("lisp", "double", "with", "escaping"))
repl:1
set('args', '("lisp", "double", "with", "escaping"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInContext (vm.js:66:16)
    at Interface.controlEval (c:\Users\bdirito\AppData\Roaming\npm\node_modules\trepanjs\lib\interface.js:345:19)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (c:\Users\bdirito\AppData\Roaming\npm\node_modules\trepanjs\lib\repl.js:290:11)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:232:10)
    at REPLServer.<anonymous> (readline.js:365:12)
    at Array.forEach (native)
(trepanjs) (trepanjs) set('args', 'vardic', 'args', 'perhaps')
args needs an Array parameter, got: vardic
```

**Comment by rocky** [comment]
Should be fixed by 0cdc15d . A bug in `show('args')` was messing up not only it, but `set(args)` as well.

In answer to your question though, an invocation looks like `set("args", ['gcd.js', 3, 5])`
